// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLmtI6WJJAuxDXlMGCKVrhoQfpEu_2u6g',
    appId: '1:835986027126:android:6b8bd1126d962adfc46557',
    messagingSenderId: '835986027126',
    projectId: 'digifarmer-dc358',
    storageBucket: 'digifarmer-dc358.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUPcmnCgMA9rMg4YfR_fBGazm355UiWy0',
    appId: '1:835986027126:ios:02224f8e7d6b72d2c46557',
    messagingSenderId: '835986027126',
    projectId: 'digifarmer-dc358',
    storageBucket: 'digifarmer-dc358.appspot.com',
    androidClientId: '835986027126-8im63jhj5riintu9onvbrbqsqbqkbs7p.apps.googleusercontent.com',
    iosClientId: '835986027126-bu3akdp8el5l32gsrhsa95t37vmi9sun.apps.googleusercontent.com',
    iosBundleId: 'com.example.digifarmer',
  );

}